package com.timevale.drc.base.mysql;

import com.google.common.collect.Sets;

import java.util.Set;

/**
 * @author gwk_2
 * @date 2021/9/22 16:40
 */
public class MySqlKeyUtil {

    /**
     * 反引号常量
     * */
    private static final String BACK_QUOTE = "`";

    public static boolean exists(String key) {
        return keys.contains(key.toUpperCase());
    }

    public static String processKeywordColumn(String columnName){
        if(!exists(columnName)){
            // 非关键字的列名，无需处理直接返回
            return columnName;
        }

        // 保留关键字使用反引号包裹
        return conv(columnName);
    }

    public static String conv(String key) {
        return BACK_QUOTE + key + BACK_QUOTE;
    }

    public static String deConv(String key) {
        if (key.startsWith(BACK_QUOTE) && key.endsWith(BACK_QUOTE)) {
            return key.substring(1, key.length() - 1);
        }
        return key;
    }

    public static Set<String> keys = Sets.newHashSet(
            "ACCOUNT",
            "AFTER",
            "ALGORITHM",
            "ALWAYS",
            "AND",
            "AT",
            "AVG",
            "BEFORE",
            "BIGINT",
            "BIT",
            "BOOL",
            "BTREE",
            "CACHE",
            "CASCADED",
            "CHAIN",
            "CHANNEL",
            "CHARSET",
            "CIPHER",
            "CLOSE",
            "COLLATE",
            "COLUMNS",
            "COMMENT",
            "COMPACT",
            "COMPRESSION",
            "CONNECTION",
            "CONSTRAINT_CATALOG",
            "CONTAINS",
            "CONVERT",
            "CROSS",
            "CURRENT_DATE",
            "CURRENT_USER",
            "DATA",
            "DATAFILE",
            "DAY",
            "DAY_MINUTE",
            "DEC",
            "DEFAULT",
            "DELAYED",
            "DESC",
            "DETERMINISTIC",
            "DISABLE",
            "DISTINCT",
            "DO",
            "DUAL",
            "DYNAMIC",
            "ELSEIF",
            "ENCRYPTION",
            "ENGINE",
            "ERROR",
            "ESCAPED",
            "EVERY",
            "EXISTS",
            "EXPIRE",
            "EXTENDED",
            "FAST",
            "FIELDS",
            "FILTER",
            "FLOAT",
            "FLUSH",
            "FORCE",
            "FOUND",
            "FULLTEXT",
            "GENERATED",
            "GET",
            "GRANT",
            "GROUP_REPLICATION",
            "HAVING",
            "HOST",
            "HOUR_MICROSECOND",
            "IDENTIFIED",
            "IGNORE_SERVER_IDS",
            "INDEX",
            "INITIAL_SIZE",
            "INSENSITIVE",
            "INSTALL",
            "INT1",
            "INT4",
            "INTERVAL",
            "IO",
            "IO_THREAD",
            "ISOLATION",
            "JOIN",
            "KEYS",
            "LANGUAGE",
            "LEAVE",
            "LESS",
            "LIMIT",
            "LINESTRING",
            "LOCAL",
            "LOCK",
            "LOGS",
            "LONGTEXT",
            "MASTER",
            "MASTER_CONNECT_RETRY",
            "MASTER_HOST",
            "MASTER_PASSWORD",
            "MASTER_SERVER_ID",
            "MASTER_SSL_CAPATH",
            "MASTER_SSL_CRL",
            "MASTER_SSL_VERIFY_SERVER_CERT",
            "MATCH",
            "MAX_QUERIES_PER_HOUR",
            "MAX_STATEMENT_TIME",
            "MEDIUM",
            "MEDIUMTEXT",
            "MESSAGE_TEXT",
            "MIGRATE",
            "MINUTE_SECOND",
            "MODE",
            "MONTH",
            "MULTIPOLYGON",
            "NAME",
            "NATURAL",
            "NDBCLUSTER",
            "NEXT",
            "NONBLOCKING",
            "NO_WAIT",
            "NUMBER",
            "OFFSET",
            "ONE",
            "OPTIMIZE",
            "OPTIONALLY",
            "ORDER",
            "OUTFILE",
            "PAGE",
            "PARTIAL",
            "PARTITIONS",
            "PLUGIN",
            "POINT",
            "PRECEDES",
            "PRESERVE",
            "PRIVILEGES",
            "PROFILE",
            "PURGE",
            "QUICK",
            "READS",
            "REAL",
            "REDOFILE",
            "REFERENCES",
            "RELAYLOG",
            "RELAY_THREAD",
            "REMOVE",
            "REPAIR",
            "REPLACE",
            "REPLICATE_IGNORE_DB",
            "REPLICATE_WILD_DO_TABLE",
            "REQUIRE",
            "RESTORE",
            "RETURN",
            "REVERSE",
            "RLIKE",
            "ROTATE",
            "ROWS",
            "RTREE",
            "SCHEMA",
            "SECOND",
            "SELECT",
            "SERIAL",
            "SESSION",
            "SHOW",
            "SIGNED",
            "SLOW",
            "SOCKET",
            "SOUNDS",
            "SPECIFIC",
            "SQLSTATE",
            "SQL_AFTER_MTS_GAPS",
            "SQL_BUFFER_RESULT",
            "SQL_NO_CACHE",
            "SQL_TSI_DAY",
            "SQL_TSI_MONTH",
            "SQL_TSI_WEEK",
            "STACKED",
            "STARTS",
            "STATS_SAMPLE_PAGES",
            "STORAGE",
            "STRING",
            "SUBPARTITION",
            "SUSPEND",
            "TABLE",
            "TABLE_CHECKSUM",
            "TEMPTABLE",
            "THAN",
            "TIMESTAMP",
            "TINYBLOB",
            "TO",
            "TRIGGER",
            "TRUNCATE",
            "UNCOMMITTED",
            "UNDOFILE",
            "UNINSTALL",
            "UNKNOWN",
            "UNTIL",
            "USAGE",
            "USER_RESOURCES",
            "UTC_DATE",
            "VALIDATION",
            "VARBINARY",
            "VARIABLES",
            "VIRTUAL",
            "WEEK",
            "WHERE",
            "WITHOUT",
            "WRITE",
            "XID",
            "FROM",
            "TO",
            "CHANNEL",
            "STATUS",
            "XID");
}
